title: Old Ballinacurra Graveyard
email: duinneacha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Information about the graves in the Old Ballinacurra Graveyard.

baseurl: "/Old-Ballinacurra-Graveyard" # the subpath of your site
url: "https://duinneacha.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: duinneacha

# Build settings
theme: minima
plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title.html

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
